# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_networkdevice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networkdevice',
            old_name='manage_ip',
            new_name='management_ip',
        ),
    ]
